### Imports

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
from datetime import date
import folium

In [5]:
#einlesen der Daten

station_data = pd.read_csv(r"D:\Benutzer\Jonathan Lanz\Dokumente\Uni\Data Science and Machine Learning\TeamProjektDaten\bluebikes_stations.csv")
data = pd.read_csv(r"D:\Benutzer\Jonathan Lanz\Dokumente\Uni\Data Science and Machine Learning\TeamProjektDaten\bluebikes_idle_time_v3.csv")

### Creating Map with all bikestations

In [3]:
station_data.dtypes

station_id      int64
lat           float64
lon           float64
dtype: object

In [4]:
#Erstellen einer Map mit allen Stationen. Herausheben der Top 10 Start- und Endstationen durch die Farbe grün.

map_boston_all = folium.Map(location=[42.3601, -71.0589], zoom_start=12)

for index, station in station_data.iterrows():
    station_id = station['station_id']
    lat = station['lat']
    lon = station['lon']

    if station_id == 67 or station_id == 80 or station_id == 22 or station_id == 68 or station_id == 189 or station_id == 178 or station_id == 74 or station_id == 190 or station_id == 36 or station_id == 53 or station_id == 107 or station_id == 190:
        folium.Marker(location=[lat, lon], icon=folium.Icon(color='green'), popup=f"Station ID: {station_id}").add_to(map_boston_all)
    else:
        folium.Marker(location=[lat, lon], popup=f"Station ID: {station_id}").add_to(map_boston_all)

map_boston_all

### Map of the top start and end stations

In [5]:
#Erstellen einer Map nur mit den Top 10 Start- und Endstationen.

map_boston_top10 = folium.Map(location=[42.3601, -71.0589], zoom_start=12)

for index, station in station_data.iterrows():
    station_id = station['station_id']
    lat = station['lat']
    lon = station['lon']

    if station_id == 67 or station_id == 80 or station_id == 22 or station_id == 68 or station_id == 189 or station_id == 178 or station_id == 74 or station_id == 190 or station_id == 36 or station_id == 53 or station_id == 107:
        folium.Marker(location=[lat, lon], icon=folium.Icon(color='green'), popup=f"Station ID: {station_id}").add_to(map_boston_top10)

map_boston_top10

### What's close to the top stations by loan-time


22: South Station

36: Boston Public Library

53: Beacon Street/Massachusetts Ave, Harvard Bridge

67: Amherst Street/Massachusetts Ave, Harvard Bridge, many sport-stadiums and sport-fields, MIT buildings, many gardens and sightseeing attractions, big student residence

68: Central Station

74: Harvard University

80: Vassar Street, Kendal Square (many buildings of technology companies and other kinds of companies, many Buildings of the MIT including MIT museum, many Restaurants)

107: Main Street/Ames Street, Kendal Square (many buildings of technology companies and other kinds of companies, many Buildings of the MIT including MIT museum, many Restaurants)

178: many big student residences

189: Main Street/Broadway, Kendal Square (many buildings of technology companies and other kinds of companies, many Buildings of the MIT including MIT museum, many Restaurants)

190: North Station

### Determining the top most used routes

In [6]:
#Data nach Start- und Endstationen gruppieren und dann Absteigend sortieren

data_station_pairs = data.groupby(['start_station_id', 'end_station_id']).size()
data_station_pairs.sort_values(ascending=False)

start_station_id  end_station_id
53                67                10344
67                53                 9854
179               80                 8388
178               80                 7919
67                179                7845
                                    ...  
8                 200                   1
                  199                   1
190               128                   1
8                 192                   1
378               378                   1
Length: 45299, dtype: int64

In [7]:
#Erstellen einer Map nur mit den Top 10 Start- und Endstationen.

map_boston_routes = folium.Map(location=[42.3601, -71.0589], zoom_start=12)

for index, station in station_data.iterrows():
    station_id = station['station_id']
    lat = station['lat']
    lon = station['lon']

    if station_id == 67 or station_id == 80 or station_id == 179 or station_id == 118 or station_id == 178 or station_id == 100 or station_id == 53:
        folium.Marker(location=[lat, lon], icon=folium.Icon(color='green'), popup=f"Station ID: {station_id}").add_to(map_boston_routes)

map_boston_routes

### What could be the reason for these routes to be the top 10 most used roads

53 to 67/67 to 53: Crossing the Harvard-Bridge might take too long to walk for some people (The Harvard-Bridge is 660m long)

179 to 80/80 to 179: Seems to be used mainly by students, because the one end of this route is where many big student residences are and at the other end are many buildings of the MIT.

178 to 80/80 to 178: Seems to be used mainly by students, because the one end of this route is where many big student residences are and at the other end are many buildings of the MIT.

67 to 179/179 to 67: Seems to be used mainly by students, because the one end of this route is where many big student residences are and at the other end are many buildings of the MIT, but also many sport-stadiums/sport-fields and many gardens and sightseeing attractions.

178 to 67: Seems to be used mainly by students, because the one end of this route is where many big student residences are and at the other end are many buildings of the MIT, but also many sport-stadiums/sport-fields and many gardens and sightseeing attractions.

100 to 118: Somerville Community Path is a paved rail trail which is 5.1 km long (Perfect for bicycle).

##### Problem: Somerville gehört eigentlich nicht zu Boston

### Well visited places

'boston_public_library': (42.349396, -71.078369), # Boston Public Library
'harvard_bridge_end_north': (42.357042, -71.092526), # Northern End of the Harvard Bridge
'harvard_bridge_end_south': (42.351951, -71.090056), # Southern End of the Harvard Bridge
'central_station': (42.365118, -71.103377), # Central Station (major subway station)
'student_district': (42.359743, -71.101438), # District with many huge student residences
'public_garden_and_boston_common' (42.354740, -71.066951), # Public garden and Boston Common (two famous parks in downtown Boston directly next to each other)
'prudential_center' (42.346434, -71.081613), # Prudential Center (big shopping mall)



##### Evtl:
'symphony_hall': (42.342826, -71.085658), # Symphony Hall
'massachusetts_general_hospital': (42.362534, -71.068775), # Massachusetts General Hospital
'boston_childrens_hospital': (42.337160, -71.105646), # Boston Children's Hospital
'boston_university_medical_center': (42.337462, -71.071108), # Boston University Medical Center
'new_england_aquarium': (42.359199, -71.049184), # New England Aquarium
'quincy_market': (42.360187, -71.054917), # Quincy Market


##### Problem:
'esplanade': (42.356103, -71.076861), # Esplanade is a Park at the Charles River that has many paths for bikes (Ist nur ein Punkt in der Mitte des Parks. Dieser ist aber ziemlich lang)
'somerville_community_path_western_end': (42.397776, -71.130458), # Western End of the Somerville Community Path (Der Path ist 5.1km lang. Nur die beiden Enden sind nicht sehr repräsentativ)
'somerville_community_path_eastern_end': (42.373682, -71.080105), # Eastern End of the Somerville Community Path (Der Path ist 5.1km lang. Nur die beiden Enden sind nicht sehr repräsentativ)

Harvard University